services:
  - type: web
    name: erp-lite-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_USERNAME
        sync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
