# --- CONEXIÓN A POSTGRESQL (DOCKER) ---
spring.datasource.url=jdbc:postgresql://localhost:5433/erplite_db
spring.datasource.username=ruben
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- COMPORTAMIENTO DE JPA ---
# "update": Actualiza las tablas si cambias el código, pero NO borra los datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- BUENAS PRÁCTICAS ---
spring.jpa.open-in-view=false